/**
 * Dzielnice/osiedla obsługiwane przez Netię w danym mieście, używane w sekcji
 * "Dzielnice obsługiwane w {mieście}" na stronie /miasta/[slug].
 *
 * Trzymane osobno od CITIES (lib/cities.ts) i łączone po `slug` w getCityDistricts(),
 * żeby nie duplikować pełnych opisów miast w dwóch miejscach. Jeśli dla danego
 * slugu nie ma wpisu (np. nowe miasto dodane do CITIES bez dzielnic), sekcja na
 * stronie po prostu się nie wyrenderuje — patrz CityPageClient.
 */
export const CITY_DISTRICTS: Record<string, string[]> = {
  warszawa: ["Śródmieście", "Mokotów", "Ursynów", "Wola", "Praga", "Bemowo"],
  krakow: ["Stare Miasto", "Krowodrza", "Podgórze", "Dębniki", "Nowa Huta"],
  wroclaw: ["Krzyki", "Fabryczna", "Psie Pole", "Śródmieście", "Biskupin"],
  lodz: ["Śródmieście", "Teofilów", "Retkinia", "Widzew", "Bałuty"],
  poznan: ["Stare Miasto", "Jeżyce", "Grunwald", "Wilda", "Łazarz"],
  gdansk: ["Śródmieście", "Wrzeszcz", "Oliwa", "Przymorze", "Zaspa", "Jasień"],
  szczecin: ["Centrum", "Pogodno", "Niebuszewo", "Prawobrzeże", "Gumieńce", "Warszewo"],
  bydgoszcz: ["Fordon", "Bartodzieje", "Śródmieście", "Szwederowo", "Osiedle Leśne", "Kapuściska"],
  lublin: ["Śródmieście", "Czechów", "Felin", "LSM", "Kalinowszczyzna", "Bronowice", "Tatary"],
  katowice: ["Śródmieście", "Ligota-Panewniki", "Brynów", "Dąb", "Załęże", "Piotrowice-Ochojec", "Giszowiec", "Wełnowiec", "Zawodzie"],
  bialystok: ["Centrum", "Antoniuk", "Wysoki Stoczek", "Piaski", "Bacieczki", "Sienkiewicza", "Leśna Dolina"],
  czestochowa: ["Tysiąclecie", "Raków", "Częstochówka-Parkitka", "Trzech Wieszczów", "Wrzosowiak", "Zawodzie-Dąbie", "Podjasnogórska", "Ostatni Grosz", "Północ", "Stradom"],
  radom: ["Śródmieście", "Gołębiów", "Ustronie", "Nad Potokiem", "Planty", "Borki", "Michałów", "Osiedle Akademickie", "Ogończyk", "Idalin"],
  torun: ["Chełmińskie", "Rubinkowo", "Na Skarpie", "Bydgoskie", "Stare Miasto", "Podgórz", "Kaszczorek", "Wrzosy", "Bielawy", "Jar"],
  kielce: ["Ślichowice", "Słoneczne Wzgórze", "Świętokrzyskie", "Herby", "Szydłówek", "KSM", "Baranówek", "Czarnów", "Bukówka", "Podkarczówka"],
  rzeszow: ["Śródmieście", "Nowe Miasto", "Baranówka", "Drabinianka", "Staroniwa", "Zalesie", "Słocina", "Przybyszówka", "Wilkowyja", "Pobitno"],
  gliwice: ["Śródmieście", "Trynek", "Sikornik", "Sośnica", "Łabędy", "Zatorze", "Bojków", "Brzezinka", "Ligota Zabrzańska", "Ostropa"],
  olsztyn: ["Śródmieście", "Jaroty", "Pojezierze", "Zatorze", "Nagórki", "Redykajny", "Dajtki", "Kortowo", "Kormoran", "Brzeziny"],
  zabrze: ["Centrum Południe", "Centrum Północ", "Zaborze", "Mikulczyce", "Biskupice", "Rokitnica", "Helenka", "Maciejów", "Kończyce", "Guido"],
  bytom: ["Śródmieście", "Szombierki", "Miechowice", "Stroszek", "Rozbark", "Karb", "Łagiewniki", "Bobrek", "Sucha Góra", "Górniki"],
  "zielona-gora": ["Centrum", "Łężyca", "Osiedle Pomorskie", "Osiedle Śląskie", "Chynów", "Nowe Miasto", "Jędrzychów", "Przylep", "Zastalowskie", "Skarpa"],
  "ruda-slaska": ["Nowy Bytom", "Wirek", "Halemba", "Kochłowice", "Godula", "Orzegów", "Bielszowice", "Chebzie", "Bykowina", "Ruda"],
  tychy: ["Śródmieście", "Paprocany", "Osiedle Z", "Osiedle A", "Osiedle B", "Osiedle C", "Osiedle D", "Osiedle E", "Wilkowyje", "Czułów"],
  "dabrowa-gornicza": ["Centrum", "Gołonóg", "Ząbkowice", "Reden", "Strzemieszyce", "Piekło", "Mydlice", "Pogoria", "Łęka", "Tworzeń"],
  elblag: ["Śródmieście", "Zawada", "Nad Jarem", "Zatorze", "Nad Zalewem", "Sadyba", "Dąbrowa", "Słoneczne", "Jakubowo", "Dolina Jagiellońska"],
  plock: ["Stare Miasto", "Podolszyce", "Imielnica", "Kolegialna", "Radziwie", "Borowiczki", "Kostrogaj", "Międzytorze", "Dzielnica Przemysłowa", "Wyszogrodzka"],
  opole: ["Śródmieście", "Zaodrze", "Nowa Wieś Królewska", "Malinka", "Groszowice", "Szczepanowice", "Kolonia Gosławicka", "Półwieś", "Wrzoski", "Czarnowąsy"],
  gdynia: ["Śródmieście", "Redłowo", "Orłowo", "Chylonia", "Obłuże", "Witomino", "Grabówek", "Karwiny", "Pogórze", "Dąbrowa"],
  tarnow: ["Centrum", "Mościce", "Klikowa", "Rzędzin", "Chyszów", "Grabówka", "Krakowska", "Strusina", "Piaskówka", "Gumniska"],
  walbrzych: ["Śródmieście", "Biały Kamień", "Sobięcin", "Podgórze", "Poniatów", "Piaskowa Góra", "Nowe Miasto", "Szczawienko", "Podzamcze"],
  koszalin: ["Śródmieście", "Północ", "Jamno-Łabusz", "Unii Europejskiej", "Rokosowo", "Tysiąclecia", "Na Skarpie", "Lechitów", "Morskie", "Władysława IV"],
  rybnik: ["Śródmieście", "Boguszowice", "Chwałowice", "Niedobczyce", "Paruszowiec", "Ligota", "Popielów", "Kamień", "Maroko-Nowiny", "Smolna"],
  "gorzow-wielkopolski": ["Śródmieście", "Manhattan", "Górczyn", "Piaski", "Słoneczne", "Staszica", "Zawarcie", "Zakanale", "Janice", "Wieprzyce"],
  chorzow: ["Centrum", "Chorzów Batory", "Chorzów II", "Chorzów Stary", "Maciejkowice", "Klimzowiec", "Osiedle Ruchu", "Nowy Batory", "Górne Łagiewniki", "Podlesie"],
  wloclawek: ["Śródmieście", "Zazamcze", "Południe", "Zawiśle", "Michelin", "Kazimierza Wielkiego", "Osiedle Mielęcin", "Rakutowo", "Śródmieście-Wschód", "Zazamcze-Północ"],
  kalisz: ["Śródmieście", "Dobrzec", "Piskorzewie", "Widok", "Asnyka", "Tyniec", "Rogatka", "Szczypiorno", "Chmielnik", "Korczak"],
  legnica: ["Śródmieście", "Piekary", "Osiedle Kopernik", "Fabryczna", "Zakaczawie", "Asnyka", "Tarninów", "Zosinek", "Bielany", "Stare Piekary"],
  grudziadz: ["Śródmieście", "Rządz", "Tarpno", "Strzemięcin", "Mniszek", "Kopernika", "Lotnisko", "Chełmińskie", "Nowa Wieś", "Owczarki"],
  slupsk: ["Śródmieście", "Nadrzecze", "Zatorze", "Westerplatte", "Niepodległości", "Piastów", "Ryczewo", "Siedlisko", "Hubalczyków", "Zamkowe"],
  "jastrzebie-zdroj": ["Zdrój", "Arki Bożka", "Osiedle 1000-lecia", "Barbary", "Moszczenica", "Borynia", "Szeroka", "Ruptawa", "Zofiówka", "Pawłowice (okolice)"],
  "nowy-sacz": ["Centrum", "Gołąbkowice", "Millenium", "Barskie", "Kochanowskiego", "Zabełcze", "Piątkowa", "Nawojowska", "Dąbrówka Polska", "Chruślice"],
  siedlce: ["Śródmieście", "Północne", "Południowe", "Sekuła", "Roskosz", "Nowe Siedlce", "Trójkąt", "Wola", "Brzeska", "Targowa"],
  "jelenia-gora": ["Cieplice Śląskie", "Sobieszów", "Czarne", "Centrum", "Zabobrze", "Maciejowa", "Goduszyn", "Strupice", "Park Sudecki", "Osiedle XX-lecia"],
  pila: ["Śródmieście", "Górne", "Koszyce", "Zamość", "Podlasie", "Staszyce", "Gładyszewo", "Grodzisko", "Zielona Dolina", "Jadwiżyn"],
  myslowice: ["Centrum", "Brzęczkowice", "Janów Miejski", "Kosztowy", "Ławki", "Morgi", "Wesoła", "Krasowy", "Bończyk", "Piasek"],
  inowroclaw: ["Śródmieście", "Solno", "Rąbin", "Nowe Osiedle", "Mątwy", "Piątek", "Stare Miasto", "Szymborze", "Osiedle Toruńskie", "Cegielnia"],
  "piotrkow-trybunalski": ["Śródmieście", "Piastowskie", "Słowackiego", "Szczekanica", "Wierzeje", "Bełzacka", "Bugaj", "Kwiatowa", "Łódzka Wschód", "Wyzwolenia"],
  "ostrow-wielkopolski": ["Śródmieście", "Parcele Zacharzewskie", "Pruślin", "Kamienice Stare", "Wenecja", "Koszary", "Zębców", "Nowe Parcele", "Osiedle Bajkowe", "Parcele Południowe"],
  konin: ["Centrum", "Chorzeń", "Zatorze", "Gosławice", "Morawczyn", "Czarków", "Glinka", "Pątnów", "Nowy Dwór", "Niesłusz"],
  suwalki: ["Centrum", "Północ", "Kamena", "Hańcza", "Papiernia", "Zastawie", "Sobolewo", "Krzywe", "Osiedle Północ II", "Osiedle Reja"],
  stargard: ["Centrum", "Osiedle Chopina", "Osiedle Pyrzyckie", "Osiedle Zachód", "Klettendorf", "Osiedle Lotnisko", "Osiedle Hallera", "Osiedle Tysiąclecia", "Letnie", "Starówka"],
  glogow: ["Śródmieście", "Kopernik", "Chrobry", "Piastów", "Hutnik", "Brzostów", "Słodowa", "Nosocice", "Krzekotów", "Przemków"],
  "siemianowice-slaskie": ["Centrum", "Michałkowice", "Bytków", "Przełajka", "Huta Laura", "Bańgów", "Tuwim", "Józefowiec (granica)", "Huta Jedność", "Bańgów-Kuźnica"],
  gniezno: ["Śródmieście", "Winiary", "Tysiąclecia", "Ustronie", "Grunwaldzkie", "Piekary", "Pustachowa", "Arkuszewo", "Dalki", "Skiereszewo"],
  "ostrowiec-swietokrzyski": ["Centrum", "Hutnicze", "Stawki", "Ogrody", "Klimkiewiczów", "Częstocice", "Osiedle Słoneczne", "Osiedle Pułanki", "Denków", "Romanów"],
  leszno: ["Śródmieście", "Gronowo", "Zatorze", "Zamenhofa", "Zacisze", "Nowe Miasto", "Piątkowo", "Antonińskie", "Gronówko", "Smoczyk"],
  zamosc: ["Stare Miasto", "Nowe Miasto", "Planty", "Karolówka", "Orzeszkowej", "Partyzantów", "Promyk", "Rataja", "Słoneczny Stok", "Majdan"],
  pabianice: ["Centrum", "Bugaj", "Piaski", "Zatorze", "Karniszewice", "Stare Miasto", "Dąbrowa", "Jutrzkowice", "Stary Bugaj", "Sereczyn"],
  "tarnowskie-gory": ["Centrum", "Bobrowniki", "Lasowice", "Rybna", "Repty", "Strzybnica", "Sowice", "Osada Jana", "Stare Tarnowice", "Pniowiec"],
  chelm: ["Centrum", "Dyrekcja", "Lwowskie", "Chełm-Południe", "Bazylany", "Słoneczne", "Słoneczny Stok", "Kościuszki", "Rejowiecka", "Cementownia"],
  lomza: ["Łomżyca", "Piaski", "Stara Łomża", "Konstantynowo", "Tysiąclecia", "Olszynki", "Zamiejska", "Centrum", "Stare Miasto", "Polowa"],
  przemysl: ["Centrum", "Zasanie", "Kazanów", "Lipowica", "Zamieście", "Bakończyce", "Winna Góra", "Kmiecie", "Rycerskie", "Łukawiec"],
  swidnica: ["Stare Miasto", "Centrum", "Osiedle Młodych", "Zarzecze", "Słowiańska", "Zawiszów", "Osiedle Słowiańskie", "Park Centralny", "Krzyże", "Bolesława Chrobrego"],
  "piekary-slaskie": ["Brzeziny", "Dąbrówka Wielka", "Kamień", "Kozłowa Góra", "Szarlej", "Osiedle Wieczorka", "Brzozowice", "Andaluzja", "Michałkowice (granica)", "Cisówka"],
  bedzin: ["Centrum", "Łagisza", "Grodziec", "Małobądz", "Ksawera", "Warpie", "Gzichów", "Górki", "Syberka", "Wiejska"],
  ostroleka: ["Centrum", "Osiedle Centrum", "Stacja", "Wojciechowice", "Pomian", "Łazek", "Starosty Kosa", "Osiedle Dzieci Polskich", "Osiedle Sienkiewicza", "Osiedle Traugutta"],
  boleslawiec: ["Centrum", "Stare Miasto", "Bolesławice", "Bolesławiec Wschód", "Bolesławiec Zachód", "Plac Wolności", "Górne Przedmieście", "Dolne Przedmieście"],
  zgorzelec: ["Centrum", "Osiedle Łużyckie", "Osiedle Zachód", "Bohaterów Getta", "Osiedle Sportowe", "Sławnikowice (granica)", "Ujazd", "Górne Miasto", "Dolne Miasto", "Osiedle Tylice"],
};

/** Zwraca listę dzielnic dla danego slugu, lub undefined, jeśli miasto nie ma jeszcze przypisanych dzielnic (np. Lubin). */
export function getCityDistricts(slug: string): string[] | undefined {
  return CITY_DISTRICTS[slug];
}
